### ISSUE TITLE
Photo archive weird navigation

### ISSUE THREAD

**Issue by jarvist** [iccavingrepo/icccsite#2]
Starting from here:-
https://union.ic.ac.uk/rcc/caving/photo_archive/

For starters, very little of the photo archive is actually linked to. 
On latest Chrome / Mac, the 'Trips', 'Tours' and 'Expeditions' buttons don't do anything, the 'Photos' button then links to the Curator /dirindex.html

This doesn't seem like intended behaviour.

**Comment by rhyst** [comment]
What linked you to that?

https://union.ic.ac.uk/rcc/caving/photo_archive/dirindex.html

Should go to that ^^^

**Comment by rhyst** [comment]
Fixed by removing that index.html and symlinking to the correct dirindex.html. 

Did you click on a link to get to that or were you just trying the url?

**Comment by jarvist** [comment]
Lots of things have dropped me here;
   clicking on 'root of photoarchive' from here for instance:
https://union.ic.ac.uk/rcc/caving/photo_archive/trips/2015-01-23%20-%20mendips/CeciliaKan_P1250629.html
-->
https://union.ic.ac.uk/rcc/caving/photo_archive/

I think I triggered it this time by trying to navigate 'up' from a Slov2009
photo

**Comment by rhyst** [comment]
Ah, okay. Is it fixed for you now?

**Comment by jarvist** [comment]
I'll reopen the issue if I trigger it again from anywhere.
