### ISSUE TITLE
Spell check on the Github editor

### ISSUE THREAD

**Issue by jarvist** [iccavingrepo/icccsite#6]
No spell check on the Github editor.

I guess this problem might be impossible to solve. The Github Wiki pages do have a spell check though.

Perhaps there's someway we could at least have a normal 'edit' window somewhere, to show the red underlining? 

I ended up copy + pasting my trip report into a Gmail, and then wiggling the mouse until it spell checked!

**Comment by rhyst** [comment]
Not sure if there's anything to do about the github edit interface. I have a greasemonkey script that enable spellcheck but I understand its moderately involved to get that set up.

I have been working on a sort of 'easy' editor: 
https://union.ic.ac.uk/rcc/caving/apps/editor/?state=content/trip/wales/wales-2017-10-13.md
Hooks up to the github api for auth and editing. Could easily enable spellcheck on that. Not sure if its preferable to the github editor atm though.

**Comment by rhyst** [comment]
Of course you can also download the repo and edit in whatever editor you want.

**Comment by jarvist** [comment]
Even just having a hot-link to open it in a simple markdown editor with a 'spell check' edit field would be useful.

We used to use this on the PHP website, for drafting trip reports. It was quite nice in that you had live feedback on the rendering, and spell check.
https://union.ic.ac.uk/rcc/caving/old/showdown/

**Comment by rhyst** [comment]
Did you click my link?

**Comment by rhyst** [comment]
You can do https://union.ic.ac.uk/rcc/caving/apps/editor/?state=new for a blankish template.

There is also already a tiny link at the bottom of every trip report to take you to the editable version. Is that what you meant?

**Comment by jarvist** [comment]
Yes, I did click the link, look at the requested permissions & think there is no-way I should authorise it. 
![image](https://user-images.githubusercontent.com/82852/32443255-40ad7a7c-c2f6-11e7-9276-0d5351e500f4.png)

Maybe make it iccavingrepo only?

**Comment by rhyst** [comment]
Haha, I can see why that would be an issue. Unfortunately there's no way to specify the repo. A limitation of github oauth. 

Essentially behind that auth is exactly what you're describing with some extras to emulate the cavepeeps and photos metadata stuff so you see a fairly accurate represantion of the final built article in a preview. Also trys to warn you if the metadata is wrong.

I could make that accessible without the auth. I'll post here when I've done that and you can see if it does what you want.

**Comment by rhyst** [comment]
(Not for jarv, note to me)

https://developer.github.com/v3/guides/managing-deploy-keys/

deploy key on server, less invasive permission on oauth token, just need to check users permissions on iccc repo. lose user info for commit message?

**Comment by rhyst** [comment]
github app (not oauth app) actually looks like an almost perfect drop in replacement:
https://developer.github.com/apps/building-integrations/setting-up-and-registering-github-apps/identifying-users-for-github-apps/

**Comment by rhyst** [comment]
Okay @jarvist that should have some significantly less scary permissions now. Let me know what you think.

**Comment by rhyst** [comment]
Closing because there are a number of options and no further work will be done to resolve this issue.
- Browser extension for Github editing (e.g. Greasemonkey script)
- Custom web app on ICCC website
- Clone the repo and use text editor of choice to edit
- Copy/pasting trip report into GMail and wiggling mouse until it spell checks

**Comment by jarvist** [comment]
Interestingly, Bitbucket have the 'spell check' turned on in their on-line editor.

I don't think this issue should be closed - because it ain't fixed! And there's plenty of spelling errors in recent trip reports...

**Comment by rhyst** [comment]
Closing because there are a number of options and no further work will be done to resolve this issue.

**Comment by jarvist** [comment]
Sad times.

**Comment by phuein** [comment]
`<div class="CodeMirror-code" role="presentation" autocorrect="off" autocapitalize="off" spellcheck="false" contenteditable="true" tabindex="0" style="">`

Changing spellcheck to "true" enabled spellchecking for me. Odd that there isn't a toggle for it somewhere visible. Very necessary when commenting code and when writing a markdown.
