### ISSUE TITLE
Finer control over the per-trip formatting

### ISSUE THREAD

**Issue by jarvist** [iccavingrepo/icccsite#7]
When there are large trips (such as the Fresher trips) to large cave systems, it is very general & not clear which trips are being written up.

I did this by hand for a recent trip report,
https://github.com/iccavingrepo/icccsite/blame/7b47a234df946195c2bc119bad58ecdbaff6035d/content/trip/wales/wales-2017-10-13.md#L127

But it would be nice if it were part of the metadata system.

**Comment by rhyst** [comment]
Do you want to be able to split up the OFD trip into the groups (I agree that would be nice) or do you want that and the part of the cave people went to (trickier)?

**Comment by jarvist** [comment]
I think split-up of the trip, so it's obvious what the groups are, and then that leaves it open for people to add their own (non cross-checking) ### markup to use as a subtitle for their trip if they so wish.

**Comment by rhyst** [comment]
I will see what can be done!

**Comment by rhyst** [comment]
This is now possible. If you have metadata like this:

```
DATE=2017-10-28; CAVE=Ogof Agen Allwedd; PEOPLE=Caver A, Caver B;
DATE=2017-10-28; CAVE=Ogof Agen Allwedd; PEOPLE=Caver C, Caver D;
DATE=2017-10-28; CAVE=Ogof Agen Allwedd; PEOPLE=Caver E; Caver F;
 ```

Then you can write:

```
Group 1: {{ DATE=2017-10-28; CAVE=Ogof Agen Allwedd;1 }}
Group 2: {{ DATE=2017-10-28; CAVE=Ogof Agen Allwedd;2 }}
Group 3: {{ DATE=2017-10-28; CAVE=Ogof Agen Allwedd;3 }}
```

Note the number at the end. This references the nth occurence of that date/cave combination. So this will produce:

```
Group 1: Caver A, Caver B
Group 2: Caver C, Caver D
Group 3: Caver E, Caver F
```

(where the caver names would be links). The usual method without the group reference still works to get a list of everyone:

```
Everyone: {{ DATE=2017-10-28; CAVE=Ogof Agen Allwedd; }}
```

To produce:

```
Everyone: Caver A, Caver B, Caver C, Caver D, Caver E, Caver F
```

**Comment by rhyst** [comment]
Can be seen on this report:

https://github.com/iccavingrepo/icccsite/blob/master/content/trip/wales/wales-2017-10-27.md
https://union.ic.ac.uk/rcc/caving/articles/wales-2017-10-27.html
